name: CENTURI_Poulain_GlobSeg

channels:
    - conda-forge
    
dependencies:
    - python=3.9
    - pyqt=5.12.3
    - numpy
    - scipy
    - scikit-image
    - matplotlib-base
    - joblib
    - napari
    - esri::tensorflow-gpu
    - pip
    - pip:
    	- stardist
